config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'tasks#index'
  # get     'login',   to: 'sessions#new'
  # post    'login',   to: 'sessions#create'
  # delete  'logout',  to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :users
  
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :ensure_has_name
  after_update :update_admin_count
  before_destroy :destroy_admin_count

  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  # validates :password_digest, presence: true
  validates :password, presence: true, length: { minimum: 6 }
  before_validation { email.downcase! }

  has_many :tasks, dependent: :destroy

  private

  def ensure_has_name
    self.name = 'NoNameUser' if name.blank?
  end

  def destroy_admin_count
    throw(:abort) if User.where(admin: true).length == 1 && self.admin?
  end

  def update_admin_count
    throw(:abort) if User.where(admin: true).length == 0
  end
end

# def self.new_remember_token
#   SecureRandom.urlsafe_base64
# end

# def self.encrypt(token)
#   Digest::SHA256.hexdigest(token.to_s)
# end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :admin_user
  
    def index
      @users = User.all
    end
  
    def show
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_user_path(@user), notice: '作成成功'
      else
        render :new, notice: '作成できませんでした'
      end
    end
  
    def update
      if @user.update(user_params)
        redirect_to admin_user_path(@user), notice: '更新できました'
      else
        render :edit, notice: '編集できませんでした'
      end
    end
  
    def destroy
      if @user.destroy
        redirect_to admin_users_path, notice: '削除できました'
      else
        redirect_to admin_users_path, notice: '削除できませんでした'
      end
    end
  
    private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index, :show]
  before_action :logout_recomend, only: [:new]
  before_action :ensure_correct_user, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit  
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
      log_in @user
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to user_path(@user), notice: 'User was successfully destroyed.'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field  :password %>
  </div>
  
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field  :password_confirmation %>
  </div>

  <%
=begin%>
 <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div> 
<%
=end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>パスワード</th>
      <th>管理者権限</th>
      <th>タスクの数</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.admin %></td>
        <td><%= user.tasks.count %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>ユーザー詳細ページ</h1>
<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>管理者権限:</strong>
  <%= @user.admin %>
</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detaile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.detaile %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task, class: "btn btn-info"  %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-success"  %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>